import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Circle, Download, ExternalLink, FileText, Mic, MicOff, Play, RotateCcw, Save, Square, TimerReset, Upload, Video, X } from 'lucide-react';
import { AppShell, PageHeader } from '../../components/AppShell.jsx';
import { useAuth } from '../../context/AuthContext.jsx';
import { useAppData } from '../../context/AppDataContext.jsx';
import { api } from '../../api.js';
import { CAREER_RESOURCES, INTERVIEW_QUESTIONS, OFFICIAL_LINKS } from './careerContent.js';

const TITLES={mock:"Simulation d’entretien",cv:'Correction de CV',hr:'Simulation RH',questions:'Questions fréquentes',feedback:'Feedback personnalisé',workshop:'Atelier pratique'};

export default function CareerToolPage(){
  const {tool}=useParams(); const navigate=useNavigate(); const {token}=useAuth(); const {notify}=useAppData();
  const [dashboard,setDashboard]=useState({resources:[],questions:[],cv_submissions:[],stats:{attempts:0,avg_confidence:0},attempts:[]});
  useEffect(()=>{if(token)api.getCareerDashboard(token).then(setDashboard).catch(e=>notify(e.message))},[token]);
  const questions=useMemo(()=>{const fromDb=dashboard.questions?.length?dashboard.questions:INTERVIEW_QUESTIONS;return tool==='hr'?fromDb.filter(q=>q.category==='hr'||q.category==='behavioral'):fromDb},[dashboard.questions,tool]);
  return <AppShell><div className="career-tool-page"><button className="back-link" onClick={()=>navigate('/career-prep')}><ArrowLeft size={18}/> Retour à Carrière</button><PageHeader title={TITLES[tool]||'Outil carrière'} subtitle="Un espace complet pour pratiquer, produire et suivre vos progrès."/>
    {tool==='mock'&&<InterviewStudio questions={questions} token={token} notify={notify}/>} 
    {tool==='hr'&&<InterviewStudio questions={questions} token={token} notify={notify} hr/>}
    {tool==='questions'&&<QuestionBank questions={questions}/>} 
    {tool==='cv'&&<CvStudio token={token} notify={notify} submissions={dashboard.cv_submissions||[]}/>} 
    {tool==='feedback'&&<FeedbackStudio dashboard={dashboard}/>} 
    {tool==='workshop'&&<WorkshopStudio navigate={navigate}/>} 
  </div></AppShell>
}

function InterviewStudio({questions,token,notify,hr=false}){
  const [idx,setIdx]=useState(0),[answer,setAnswer]=useState(''),[confidence,setConfidence]=useState(3),[seconds,setSeconds]=useState(120),[running,setRunning]=useState(false);
  const [recording,setRecording]=useState(false),[audioUrl,setAudioUrl]=useState(''); const recorder=useRef(null),chunks=useRef([]);
  const q=questions[idx%Math.max(1,questions.length)];
  useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(t)},[running]);
  async function toggleRecord(){if(recording){recorder.current?.stop();setRecording(false);return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{setAudioUrl(URL.createObjectURL(new Blob(chunks.current,{type:r.mimeType})));stream.getTracks().forEach(t=>t.stop())};r.start();recorder.current=r;setRecording(true)}catch(e){notify('Microphone indisponible : '+e.message)}}
  async function save(){if(!q||!answer.trim())return;try{await api.saveCareerPractice({question_id:q.id?.includes?.('-')?null:q.id,answer_text:answer,confidence},token);notify('Entraînement enregistré');setAnswer('')}catch(e){notify(e.message)}}
  return <div className="career-studio-layout"><aside className="career-question-list"><h3>{hr?'Entretien RH':'Entretien complet'}</h3>{questions.map((item,i)=><button key={item.id||i} className={i===idx?'active':''} onClick={()=>{setIdx(i);setSeconds(120);setRunning(false)}}><span>{i+1}</span>{item.question}</button>)}</aside><main className="career-workspace">
    <div className="workspace-toolbar"><span className="timer-pill"><TimerReset size={18}/>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</span><button onClick={()=>setRunning(!running)}>{running?'Pause':'Démarrer le chrono'}</button><button onClick={()=>{setSeconds(120);setRunning(false)}}><RotateCcw size={16}/> Réinitialiser</button></div>
    <div className="career-big-question"><span>Question {idx+1} / {questions.length}</span><h2>{q?.question}</h2><p>{q?.guidance}</p></div>
    {q?.sample&&<details className="answer-example"><summary>Voir un exemple de structure</summary><p>{q.sample}</p></details>}
    <label className="career-answer-box">Votre réponse<textarea value={answer} onChange={e=>setAnswer(e.target.value)} rows="9" placeholder="Structurez votre réponse ici…"/></label>
    <div className="record-panel"><button className={recording?'recording':''} onClick={toggleRecord}>{recording?<><Square/>Arrêter</>:<><Mic/>Enregistrer ma réponse</>}</button>{audioUrl&&<audio controls src={audioUrl}/>}</div>
    <div className="self-review"><h3>Auto-évaluation</h3><div className="confidence-row"><span>Confiance</span>{[1,2,3,4,5].map(n=><button className={confidence===n?'active':''} onClick={()=>setConfidence(n)} key={n}>{n}</button>)}</div><ul><li>Réponse structurée et concise</li><li>Exemple concret</li><li>Résultat ou impact</li><li>Lien avec le poste</li></ul></div>
    <div className="workspace-actions"><button onClick={()=>{setIdx(i=>(i+1)%questions.length);setAnswer('');setSeconds(120)}}>Question suivante</button><button className="primary-btn" disabled={!answer.trim()} onClick={save}><Save size={17}/>Enregistrer</button></div>
  </main></div>
}

function QuestionBank({questions}){const [search,setSearch]=useState(''),[cat,setCat]=useState('all');const filtered=questions.filter(q=>(cat==='all'||q.category===cat)&&`${q.question} ${q.guidance}`.toLowerCase().includes(search.toLowerCase()));return <section className="career-content-panel"><div className="career-bank-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher une question…"/><div>{['all','hr','behavioral','technical'].map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c==='all'?'Toutes':c==='hr'?'RH':c==='behavioral'?'Comportemental':'Technique'}</button>)}</div></div><div className="question-bank-grid">{filtered.map((q,i)=><details key={q.id||i}><summary><span>{i+1}</span>{q.question}</summary><p><b>Comment répondre :</b> {q.guidance}</p>{q.sample&&<p><b>Structure possible :</b> {q.sample}</p>}</details>)}</div></section>}

function CvStudio({token,notify,submissions}){const [file,setFile]=useState(null),[title,setTitle]=useState('Mon CV'),[checks,setChecks]=useState({});const items=CAREER_RESOURCES.find(r=>r.slug==='cv').items;const score=Math.round(Object.values(checks).filter(Boolean).length/items.length*100);async function upload(){if(!file)return notify('Choisissez un fichier');try{await api.uploadCareerCv({file,title},token);notify('CV envoyé et enregistré');setFile(null)}catch(e){notify(e.message)}}return <div className="career-cv-layout"><section className="career-content-panel"><h2>1. Envoyer votre CV</h2><p>Formats acceptés : PDF, DOC, DOCX. Le fichier est stocké dans votre espace personnel.</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Titre du CV"/><label className="cv-dropzone"><Upload size={34}/><b>{file?file.name:'Choisir un CV sur votre ordinateur'}</b><small>Maximum 15 Mo</small><input type="file" accept=".pdf,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary-btn" onClick={upload} disabled={!file}><Upload size={17}/> Envoyer le CV</button>{submissions.length>0&&<div className="cv-submission-list"><h3>Historique</h3>{submissions.map(s=><div key={s.id}><FileText/><span><b>{s.title}</b><small>{s.file_name} · {s.status}</small></span>{s.file_url&&<a href={s.file_url} target="_blank" rel="noreferrer"><ExternalLink/></a>}</div>)}</div>}</section><section className="career-content-panel"><div className="audit-score"><strong>{score}%</strong><span>Score de préparation</span></div><h2>2. Audit en 15 points</h2><div className="cv-audit-list">{items.map((x,i)=><label key={x}><button onClick={()=>setChecks(c=>({...c,[i]:!c[i]}))}>{checks[i]?<CheckCircle2/>:<Circle/>}</button><span>{x}</span></label>)}</div><div className="audit-advice"><h3>Interprétation</h3><p>{score<50?'Votre CV nécessite encore plusieurs corrections structurantes.':score<80?'Votre CV est sur une bonne base. Travaillez les éléments restants.':'Votre CV est prêt pour une dernière relecture et adaptation à chaque offre.'}</p></div></section></div>}

function FeedbackStudio({dashboard}){const attempts=dashboard.attempts||[];const confidence=Number(dashboard.stats?.avg_confidence||0);return <><div className="feedback-dashboard"><article><strong>{dashboard.stats?.attempts||0}</strong><span>entraînements</span></article><article><strong>{confidence}/5</strong><span>confiance moyenne</span></article><article><strong>{dashboard.cv_submissions?.length||0}</strong><span>CV suivis</span></article></div><section className="career-content-panel"><h2>Plan d’amélioration personnalisé</h2><div className="feedback-roadmap"><div><CheckCircle2/><span><b>1. Répéter les réponses fondamentales</b><small>Présentation, motivation, force, faiblesse et projet.</small></span></div><div><CheckCircle2/><span><b>2. Préparer cinq histoires STAR</b><small>Conflit, erreur, réussite, leadership, apprentissage.</small></span></div><div><CheckCircle2/><span><b>3. Enregistrer deux simulations</b><small>Écoutez le débit, les répétitions et la durée.</small></span></div><div><CheckCircle2/><span><b>4. Adapter le CV à l’offre</b><small>Compétences, mots-clés et résultats mesurables.</small></span></div></div></section><section className="career-content-panel"><h2>Conseils ciblés</h2><p>{confidence<3?'Votre confiance est encore basse : commencez par des réponses courtes et répétées. La répétition crée de la fluidité.':'Votre confiance progresse : concentrez-vous maintenant sur la précision des exemples et la mesure des résultats.'}</p></section></>}

function WorkshopStudio({navigate}){return <><div className="workshop-grid">{CAREER_RESOURCES.slice(0,8).map(r=><article key={r.slug}><span>{r.type}</span><h3>{r.title}</h3><p>{r.summary}</p><button onClick={()=>navigate(`/career-prep/resource/${r.slug}`)}>Ouvrir l’atelier →</button></article>)}</div><section className="career-content-panel"><h2>Parcours recommandé sur 7 jours</h2><ol className="seven-day-plan"><li>Définir le poste cible et analyser une offre réelle</li><li>Adapter le CV à cette offre</li><li>Préparer le pitch de 2 minutes</li><li>Écrire 5 réponses STAR</li><li>Faire une simulation RH</li><li>Faire une simulation technique ou métier</li><li>Relire, enregistrer une dernière simulation et préparer les questions à poser</li></ol></section></>}
