export const INTERVIEW_QUESTIONS = [
  {id:'hr-1',category:'hr',question:'Présentez-vous en deux minutes.',guidance:'Structure : présent → expérience la plus pertinente → valeur que vous apportez → objectif visé.',sample:'Je suis actuellement … Mon expérience la plus pertinente est … J’y ai obtenu … Aujourd’hui, je souhaite mettre ces compétences au service de …'},
  {id:'hr-2',category:'hr',question:'Pourquoi voulez-vous rejoindre cette entreprise ?',guidance:'Montrez que vous avez étudié l’entreprise. Reliez mission, poste et contribution concrète.',sample:'Votre travail sur … m’intéresse parce que … Mon expérience en … me permettrait de contribuer à …'},
  {id:'hr-3',category:'hr',question:'Pourquoi ce poste ?',guidance:'Reliez 3 éléments : missions, compétences déjà acquises, progression recherchée.',sample:'Ce poste combine …, … et …, qui correspondent à mes expériences en …'},
  {id:'hr-4',category:'hr',question:'Pourquoi devrions-nous vous recruter ?',guidance:'Donnez trois preuves reliées aux besoins du poste, pas une liste d’adjectifs.',sample:'Je peux apporter 1) … preuve … 2) … preuve … 3) … preuve …'},
  {id:'hr-5',category:'hr',question:'Quelle est votre principale force ?',guidance:'Choisissez une force utile au poste et prouvez-la par un résultat.',sample:'Ma force principale est … Par exemple, dans … j’ai … ce qui a permis …'},
  {id:'hr-6',category:'hr',question:'Quelle est votre principale faiblesse ?',guidance:'Choisissez un axe réel mais gérable. Expliquez le plan d’amélioration et les progrès.',sample:'J’avais tendance à … J’ai mis en place … Aujourd’hui …'},
  {id:'hr-7',category:'hr',question:'Où vous voyez-vous dans cinq ans ?',guidance:'Parlez de progression de compétences et de responsabilités, pas d’un titre rigide.',sample:'Je souhaite avoir renforcé … et être capable de …'},
  {id:'hr-8',category:'hr',question:'Pourquoi quittez-vous votre poste actuel ?',guidance:'Restez positif. Parlez de recherche de progression, d’apprentissage ou d’alignement.',sample:'J’ai beaucoup appris sur … Je cherche maintenant …'},
  {id:'hr-9',category:'hr',question:'Quelles sont vos attentes salariales ?',guidance:'Donnez une fourchette argumentée par le marché, votre niveau et le périmètre du poste.',sample:'Au regard du périmètre et de mon expérience, je vise une fourchette de … à …, tout en restant ouvert au package global.'},
  {id:'hr-10',category:'hr',question:'Avez-vous des questions pour nous ?',guidance:'Préparez 3 questions sur les priorités du poste, l’équipe et les critères de réussite.',sample:'Quelles seront les trois priorités de la personne recrutée durant les 90 premiers jours ?'},
  {id:'behavioral-1',category:'behavioral',question:'Parlez d’un conflit que vous avez résolu.',guidance:'Méthode STAR : Situation, Tâche, Action, Résultat. Concentrez-vous sur votre action.',sample:'S: … T: … A: j’ai … R: …'},
  {id:'behavioral-2',category:'behavioral',question:'Racontez une erreur professionnelle.',guidance:'Assumez votre responsabilité, expliquez la correction puis la prévention.',sample:'J’ai … J’ai immédiatement … Puis j’ai ajouté … pour éviter que cela se reproduise.'},
  {id:'behavioral-3',category:'behavioral',question:'Comment gérez-vous plusieurs priorités urgentes ?',guidance:'Expliquez vos critères : impact, délai, dépendances, risque et communication.',sample:'Je clarifie d’abord … puis je classe … et je communique …'},
  {id:'behavioral-4',category:'behavioral',question:'Donnez un exemple de leadership sans autorité hiérarchique.',guidance:'Montrez comment vous avez créé de la clarté, obtenu l’adhésion et facilité l’action.',sample:'Le groupe était bloqué sur … J’ai proposé … puis … Résultat …'},
  {id:'behavioral-5',category:'behavioral',question:'Parlez d’un objectif difficile atteint.',guidance:'Quantifiez l’objectif, les obstacles, vos décisions et le résultat.',sample:'L’objectif était … L’obstacle principal … J’ai … Résultat : …'},
  {id:'behavioral-6',category:'behavioral',question:'Comment réagissez-vous à un feedback difficile ?',guidance:'Écoute, clarification, plan d’action, suivi.',sample:'Je commence par … puis je vérifie … et je définis …'},
  {id:'behavioral-7',category:'behavioral',question:'Racontez une situation où vous avez appris très vite.',guidance:'Détaillez votre méthode d’apprentissage, les sources utilisées et la preuve de maîtrise.',sample:'Je devais … en … jours. J’ai découpé … puis testé …'},
  {id:'behavioral-8',category:'behavioral',question:'Parlez d’une décision prise avec des informations incomplètes.',guidance:'Expliquez vos hypothèses, le risque acceptable et la manière de vérifier rapidement.',sample:'Il manquait … J’ai évalué … puis décidé … avec un point de contrôle …'},
  {id:'behavioral-9',category:'behavioral',question:'Comment gérez-vous le stress ?',guidance:'Citez des pratiques concrètes et un exemple réel.',sample:'Je réduis l’incertitude par … puis je protège …'},
  {id:'behavioral-10',category:'behavioral',question:'Parlez d’une collaboration difficile.',guidance:'Montrez écoute, clarification des attentes et recherche d’un objectif commun.',sample:'Nos attentes divergeaient sur … J’ai organisé …'},
  {id:'technical-1',category:'technical',question:'Expliquez un projet technique dont vous êtes fier.',guidance:'Problème → architecture/décisions → difficultés → résultat mesurable → leçon.',sample:'Le problème était … J’ai choisi … car … La difficulté … Le résultat …'},
  {id:'technical-2',category:'technical',question:'Comment abordez-vous un problème que vous ne savez pas résoudre ?',guidance:'Clarifier, reproduire, hypothèses, recherche ciblée, test, validation, documentation.',sample:'Je commence par définir … puis je construis un cas minimal …'},
  {id:'technical-3',category:'technical',question:'Comment garantissez-vous la qualité ?',guidance:'Tests, revue, automatisation, observabilité, documentation et critères d’acceptation.',sample:'Je combine … selon le risque et le coût d’une erreur.'},
  {id:'technical-4',category:'technical',question:'Racontez une erreur technique importante.',guidance:'Cause racine, impact, correction, prévention.',sample:'La cause était … J’ai corrigé … puis ajouté …'},
  {id:'technical-5',category:'technical',question:'Expliquez un concept complexe à une personne non technique.',guidance:'Commencez par le besoin, utilisez une analogie, puis vérifiez la compréhension.',sample:'Imaginez que … Dans notre système …'},
  {id:'technical-6',category:'technical',question:'Comment choisissez-vous entre deux technologies ?',guidance:'Comparez exigences, contraintes, équipe, maturité, coût total et risque.',sample:'Je définis d’abord les critères … puis je fais un prototype si …'},
  {id:'technical-7',category:'technical',question:'Comment déboguez-vous un incident en production ?',guidance:'Stabiliser, observer, réduire le périmètre, corriger, vérifier, post-mortem.',sample:'Ma priorité est d’abord … Ensuite je …'},
  {id:'technical-8',category:'technical',question:'Comment gérez-vous la dette technique ?',guidance:'Visibilité, impact métier, priorisation, prévention.',sample:'Je la rends visible via … puis je priorise selon …'},
  {id:'technical-9',category:'technical',question:'Comment documentez-vous votre travail ?',guidance:'Documenter les décisions, les interfaces et les procédures de reprise.',sample:'Je documente surtout … parce que …'},
  {id:'technical-10',category:'technical',question:'Comment estimez-vous une tâche technique ?',guidance:'Découpage, inconnues, dépendances, risque, marge et ré-estimation.',sample:'Je sépare … puis je rends explicites les inconnues …'}
];

export const CAREER_RESOURCES = [
  {slug:'star',title:'Méthode STAR : guide complet',type:'Guide',summary:'Une structure claire pour répondre aux questions comportementales.',sections:[
    ['Situation','Donnez le contexte en 2 ou 3 phrases. Ne racontez pas toute l’histoire.'],['Tâche','Précisez votre responsabilité et l’objectif attendu.'],['Action','Expliquez ce que vous avez personnellement fait. C’est la partie la plus importante.'],['Résultat','Quantifiez si possible : délai, qualité, coût, satisfaction, apprentissage.']
  ],exercise:'Préparez 5 histoires STAR : conflit, erreur, réussite, leadership, apprentissage rapide.'},
  {slug:'pitch',title:'Construire un pitch de 2 minutes',type:'Atelier',summary:'Présentez votre profil sans réciter votre CV.',sections:[['0–20 s','Qui vous êtes maintenant.'],['20–70 s','Deux expériences ou compétences qui prouvent votre valeur.'],['70–100 s','Pourquoi le poste ou le secteur vous intéresse.'],['100–120 s','La contribution que vous voulez apporter.']],exercise:'Écrivez une version de 180 à 250 mots, puis enregistrez-vous trois fois.'},
  {slug:'checklist',title:'Checklist 24 h avant l’entretien',type:'Checklist',summary:'Préparez le fond, la logistique et votre état mental.',items:['Relire l’offre et surligner les 5 exigences principales','Préparer 5 histoires STAR','Étudier l’entreprise : produits, actualité, clients, culture','Préparer 5 questions à poser','Tester caméra, micro, connexion et lien visio','Préparer CV, offre et notes sur un même dossier','Choisir tenue et trajet','Dormir suffisamment et prévoir 15 minutes d’avance']},
  {slug:'cv',title:'CV : contrôle qualité en 15 points',type:'Checklist',summary:'Un audit complet avant envoi.',items:['Titre adapté au poste','Résumé de profil en 3–5 lignes','Expériences dans l’ordre antéchronologique','Chaque expérience contient des résultats','Verbes d’action précis','Chiffres quand ils sont pertinents','Compétences alignées avec l’offre','Mots-clés de l’annonce repris naturellement','Dates cohérentes','Mise en page lisible','Une police claire','Aucune faute visible','Coordonnées à jour','Liens LinkedIn/portfolio valides','Nom de fichier professionnel']},
  {slug:'questions-to-ask',title:'25 questions à poser au recruteur',type:'Banque de questions',summary:'Choisissez 3 à 5 questions selon le moment de l’entretien.',items:['Quelles seront les priorités des 90 premiers jours ?','Comment mesurez-vous la réussite sur ce poste ?','Quels sont les défis les plus urgents de l’équipe ?','Comment se déroule l’onboarding ?','Avec quelles équipes cette personne collabore-t-elle le plus ?','Qu’est-ce qui différencie les meilleurs dans ce rôle ?','Pourquoi le poste est-il ouvert ?','Comment l’équipe prend-elle ses décisions ?','Quels sont les projets majeurs des 12 prochains mois ?','Comment évoluent les responsabilités avec l’expérience ?']},
  {slug:'technical',title:'Préparer un entretien technique',type:'Plan',summary:'Une méthode de révision en quatre étapes.',sections:[['1. Cartographier','Listez les compétences demandées dans l’offre.'],['2. Prioriser','Classez : indispensable / utile / secondaire.'],['3. Pratiquer','Résolvez des cas en expliquant votre raisonnement à voix haute.'],['4. Simuler','Faites 2 simulations chronométrées et analysez vos hésitations.']]},
  {slug:'salary',title:'Négocier son salaire',type:'Guide',summary:'Préparez votre fourchette et vos arguments.',sections:[['Marché','Collectez plusieurs repères comparables : pays, ville, secteur, niveau.'],['Valeur','Préparez 3 preuves de contribution.'],['Fourchette','Définissez cible, acceptable et plancher.'],['Package','Considérez bonus, télétravail, formation, congés, responsabilités.']],exercise:'Préparez une phrase courte : « Au regard de … je vise une fourchette de … à … ».'},
  {slug:'follow-up',title:'Relance après entretien',type:'Modèles',summary:'Trois messages prêts à personnaliser.',templates:[
    {name:'Remerciement le jour même',text:'Objet : Merci pour notre échange\n\nBonjour [Nom],\nMerci pour notre échange concernant le poste de [poste]. J’ai particulièrement apprécié notre discussion sur [sujet précis]. Elle confirme mon intérêt pour le rôle et l’équipe.\n\nJe reste disponible pour toute information complémentaire.\nBien cordialement,\n[Nom]'},
    {name:'Relance après le délai annoncé',text:'Objet : Suivi de ma candidature – [poste]\n\nBonjour [Nom],\nJe me permets de revenir vers vous au sujet de ma candidature au poste de [poste]. Notre échange du [date] a renforcé mon intérêt, notamment pour [élément précis].\n\nAuriez-vous une mise à jour sur les prochaines étapes ?\nBien cordialement,\n[Nom]'},
    {name:'Après un refus',text:'Bonjour [Nom],\nMerci de m’avoir informé de votre décision. Même si je suis déçu, j’ai apprécié nos échanges. Si vous avez la possibilité de partager un point de feedback, il m’aiderait à progresser.\n\nJe vous souhaite une bonne continuation.\nBien cordialement,\n[Nom]'}
  ]}
];

export const OFFICIAL_LINKS = [
  {title:'Créer un CV Europass',url:'https://europass.europa.eu/fr/create-europass-cv',source:'Union européenne'},
  {title:'Conseils entretien – EURES',url:'https://eures.europa.eu/5-tips-acing-your-interview-2017-05-08_fr',source:'Union européenne'},
  {title:'Préparer un entretien',url:'https://www.arbeitsagentur.de/bildung/bewerbung/bewerbungsgespraech',source:'Bundesagentur für Arbeit'},
  {title:'Documents de candidature',url:'https://www.arbeitsagentur.de/bildung/bewerbung/bewerbungsunterlagen',source:'Bundesagentur für Arbeit'}
];
