-- StudyLink 010 - Catalogue complet par categories
-- Idempotent: peut etre execute plusieurs fois.
DO $$
DECLARE
  v_author UUID;
  v_cat INTEGER;
  v_course UUID;
  v_module UUID;
  rec RECORD;
BEGIN
  SELECT id INTO v_author FROM public.users ORDER BY CASE WHEN role='admin' THEN 0 ELSE 1 END, created_at LIMIT 1;
  IF v_author IS NULL THEN RAISE EXCEPTION 'Aucun utilisateur existe. Creez d abord un compte StudyLink.'; END IF;

  FOR rec IN SELECT * FROM (VALUES
    ('python-pour-debutants-complet','Python pour débutants','Apprenez Python pas à pas et créez vos premiers programmes.','Informatique','beginner',390,'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=1200&q=80',ARRAY['Comprendre la syntaxe Python','Manipuler variables et collections','Créer un projet pratique']::text[]),
    ('java-spring-boot','Java & Spring Boot','Construisez des API REST professionnelles avec Java et Spring Boot.','Informatique','intermediate',480,'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',ARRAY['Maîtriser Java moderne','Créer une API REST','Connecter une base de données']::text[]),
    ('web-react-moderne','Développement Web avec React','Créez des interfaces web modernes, rapides et responsives.','Informatique','beginner',420,'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&q=80',ARRAY['Comprendre les composants','Gérer l’état','Construire une application complète']::text[]),
    ('cybersecurite-fondamentaux','Cybersécurité : fondamentaux','Protégez systèmes, comptes et applications contre les menaces courantes.','Informatique','beginner',360,'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&q=80',ARRAY['Comprendre les menaces','Sécuriser les accès','Appliquer les bonnes pratiques']::text[]),
    ('algebre-lineaire','Algèbre linéaire appliquée','Matrices, espaces vectoriels et applications concrètes.','Mathématiques','intermediate',420,'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=1200&q=80',ARRAY['Calculer avec les matrices','Comprendre les espaces vectoriels','Résoudre des systèmes']::text[]),
    ('analyse-calcul-differentiel','Analyse & calcul différentiel','Limites, dérivées et intégrales expliquées progressivement.','Mathématiques','beginner',450,'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1200&q=80',ARRAY['Maîtriser les limites','Calculer des dérivées','Résoudre des intégrales']::text[]),
    ('probabilites-statistiques','Probabilités & statistiques','Apprenez à analyser les données et interpréter l’incertitude.','Mathématiques','intermediate',390,'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',ARRAY['Calculer des probabilités','Comprendre les distributions','Interpréter les tests']::text[]),
    ('optimisation-mathematique','Optimisation mathématique','Modélisez et résolvez des problèmes de décision complexes.','Mathématiques','advanced',510,'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',ARRAY['Formuler un modèle','Résoudre des contraintes','Analyser la solution']::text[]),
    ('mecanique-classique','Mécanique classique','Forces, énergie et mouvement avec exercices guidés.','Physique','beginner',420,'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?auto=format&fit=crop&w=1200&q=80',ARRAY['Appliquer les lois de Newton','Étudier l’énergie','Résoudre des mouvements']::text[]),
    ('electromagnetisme','Électromagnétisme','Champs électriques, magnétisme et équations de Maxwell.','Physique','intermediate',480,'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80',ARRAY['Comprendre les champs','Analyser les circuits','Relier électricité et magnétisme']::text[]),
    ('physique-quantique','Introduction à la physique quantique','Découvrez les concepts clés du monde microscopique.','Physique','advanced',540,'https://images.unsplash.com/photo-1635070041409-e63e783ce3c1?auto=format&fit=crop&w=1200&q=80',ARRAY['Comprendre la dualité','Étudier les états quantiques','Interpréter les mesures']::text[]),
    ('physique-nucleaire','Physique nucléaire & radioprotection','Structure du noyau, rayonnements et principes de protection.','Physique','intermediate',450,'https://images.unsplash.com/photo-1581093458791-9d42e3c7bb92?auto=format&fit=crop&w=1200&q=80',ARRAY['Comprendre les rayonnements','Mesurer une dose','Appliquer la radioprotection']::text[]),
    ('allemand-b1','Allemand B1 pratique','Communiquez avec confiance dans les situations du quotidien.','Langues','intermediate',360,'https://images.unsplash.com/photo-1527866959252-deab85ef7d1b?auto=format&fit=crop&w=1200&q=80',ARRAY['Renforcer la grammaire','Développer le vocabulaire','Pratiquer l’oral']::text[]),
    ('anglais-professionnel','Anglais professionnel','Réunions, emails et présentations en anglais.','Langues','intermediate',300,'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1200&q=80',ARRAY['Rédiger des emails','Présenter un projet','Participer à une réunion']::text[]),
    ('francais-academique','Français académique','Améliorez vos écrits universitaires et professionnels.','Langues','intermediate',330,'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=80',ARRAY['Structurer un texte','Améliorer le style','Corriger les erreurs']::text[]),
    ('espagnol-debutant','Espagnol pour débutants','Les bases pour comprendre et parler espagnol.','Langues','beginner',300,'https://images.unsplash.com/photo-1509840841025-9088ba78a826?auto=format&fit=crop&w=1200&q=80',ARRAY['Se présenter','Comprendre les bases','Tenir une conversation simple']::text[]),
    ('cv-impactant','Créer un CV impactant','Construisez un CV clair, moderne et adapté au poste.','Emploi & Carrière','all',180,'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1200&q=80',ARRAY['Structurer le CV','Valoriser les compétences','Adapter au poste']::text[]),
    ('entretien-embauche','Réussir son entretien d’embauche','Préparez vos réponses et gagnez en confiance.','Emploi & Carrière','all',240,'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?auto=format&fit=crop&w=1200&q=80',ARRAY['Préparer son pitch','Répondre aux questions','Gérer le stress']::text[]),
    ('linkedin-personal-branding','LinkedIn & personal branding','Développez une présence professionnelle qui attire les opportunités.','Emploi & Carrière','all',210,'https://images.unsplash.com/photo-1611944212129-29977ae1398c?auto=format&fit=crop&w=1200&q=80',ARRAY['Optimiser son profil','Développer son réseau','Créer du contenu']::text[]),
    ('entretien-technique','Entretien technique développeur','Algorithmes, système design et méthode de résolution.','Emploi & Carrière','advanced',360,'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',ARRAY['Résoudre les exercices','Expliquer sa démarche','Préparer le système design']::text[]),
    ('discipline-30-jours-course','Discipline 30 jours','Construisez des habitudes solides et passez à l’action.','Développement personnel','beginner',240,'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',ARRAY['Créer une routine','Suivre ses habitudes','Renforcer la constance']::text[]),
    ('yoga-matin-course','Yoga du matin','Démarrez la journée avec mobilité, respiration et énergie.','Développement personnel','all',180,'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=1200&q=80',ARRAY['Améliorer la mobilité','Respirer consciemment','Créer une routine']::text[]),
    ('meditation-stress','Méditation & gestion du stress','Retrouvez le calme avec des pratiques simples et guidées.','Développement personnel','beginner',150,'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=1200&q=80',ARRAY['Respirer profondément','Observer les pensées','Réduire le stress']::text[]),
    ('productivite-focus','Productivité & concentration','Travail profond, priorités et organisation personnelle.','Développement personnel','all',210,'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1200&q=80',ARRAY['Planifier efficacement','Éliminer les distractions','Travailler en profondeur']::text[]),
    ('machine-learning-pratique','Machine Learning pratique','Créez vos premiers modèles de prédiction avec Python.','Data Science','intermediate',520,'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=1200&q=80',ARRAY['Préparer les données','Entraîner un modèle','Évaluer les performances']::text[]),
    ('data-analysis-python','Analyse de données avec Python','Pandas, visualisation et exploration de données réelles.','Data Science','beginner',420,'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',ARRAY['Nettoyer les données','Analyser avec Pandas','Créer des visualisations']::text[]),
    ('deep-learning-intro','Introduction au Deep Learning','Réseaux de neurones, entraînement et applications.','Data Science','advanced',540,'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1200&q=80',ARRAY['Comprendre les neurones','Construire un réseau','Entraîner un modèle']::text[]),
    ('sql-data-analytics','SQL pour la Data','Interrogez, transformez et analysez des bases de données.','Data Science','beginner',330,'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=80',ARRAY['Écrire des requêtes','Joindre des tables','Analyser des données']::text[]),
    ('business-plan-complet','Créer son business plan','Transformez une idée en projet structuré et convaincant.','Business','beginner',450,'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',ARRAY['Analyser le marché','Construire le modèle économique','Préparer les finances']::text[]),
    ('marketing-digital','Marketing digital','Acquisition, contenu et mesure de performance.','Business','intermediate',360,'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',ARRAY['Définir une stratégie','Créer du contenu','Mesurer les résultats']::text[]),
    ('finance-entrepreneurs','Finance pour entrepreneurs','Budget, trésorerie et rentabilité sans jargon.','Business','beginner',300,'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',ARRAY['Construire un budget','Suivre la trésorerie','Mesurer la rentabilité']::text[]),
    ('vente-negociation','Vente & négociation','Trouvez des clients, comprenez leurs besoins et concluez.','Business','intermediate',270,'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=80',ARRAY['Prospecter efficacement','Conduire un entretien','Négocier avec confiance']::text[])
  ) AS x(slug,title,description,category_name,level,estimated_minutes,cover_url,objectives) LOOP
    INSERT INTO public.learning_categories(name,slug,description)
    SELECT rec.category_name, lower(regexp_replace(rec.category_name,'[^a-zA-Z0-9]+','-','g')), 'Catalogue StudyLink'
    WHERE NOT EXISTS (SELECT 1 FROM public.learning_categories WHERE name=rec.category_name);
    SELECT id INTO v_cat FROM public.learning_categories WHERE name=rec.category_name ORDER BY id LIMIT 1;
    INSERT INTO public.courses(author_id,category_id,title,slug,short_description,description,cover_url,level,language,estimated_minutes,price,is_free,status,content_type,objectives,prerequisites,published_at)
    VALUES(v_author,v_cat,rec.title,rec.slug,rec.description,rec.description || ' Un parcours progressif avec theorie, exercices et projet pratique.',rec.cover_url,rec.level,'fr',rec.estimated_minutes,0,true,'published','course',rec.objectives,ARRAY['Motivation et regularite'],now())
    ON CONFLICT (slug) DO UPDATE SET category_id=EXCLUDED.category_id,title=EXCLUDED.title,short_description=EXCLUDED.short_description,description=EXCLUDED.description,cover_url=EXCLUDED.cover_url,level=EXCLUDED.level,estimated_minutes=EXCLUDED.estimated_minutes,status='published',objectives=EXCLUDED.objectives,published_at=COALESCE(courses.published_at,now())
    RETURNING id INTO v_course;

    INSERT INTO public.course_modules(course_id,title,description,position) VALUES(v_course,'Fondamentaux','Comprendre les concepts essentiels',1) ON CONFLICT(course_id,position) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description RETURNING id INTO v_module;
    INSERT INTO public.lessons(module_id,title,slug,lesson_type,content,duration_seconds,position,is_preview) VALUES
      (v_module,'Comprendre les bases',rec.slug||'-bases','text',rec.description,1800,1,true),
      (v_module,'Exercices essentiels',rec.slug||'-exercices','exercise','Mettez en pratique les notions du cours avec une serie d exercices guides.',2100,2,false),
      (v_module,'Projet pratique',rec.slug||'-projet','exercise','Realisez un mini-projet pour valider les competences acquises.',2700,3,false)
    ON CONFLICT(module_id,position) DO UPDATE SET title=EXCLUDED.title,content=EXCLUDED.content,duration_seconds=EXCLUDED.duration_seconds;
  END LOOP;
END $$;

SELECT lc.name AS categorie, COUNT(*) AS cours_publies FROM public.courses c JOIN public.learning_categories lc ON lc.id=c.category_id WHERE c.status='published' GROUP BY lc.name ORDER BY lc.name;
